opa:
  server: 'http://localhost:8181'
  policy-endpoint: '/v1/policies/register'
  roles-endpoint: '/v1/data/role_grants'
  users-endpoint: '/v1/data/user_roles'
  authorize-endpoint: '/v1/data/users/register/allow'
